package com.gcaguilar.beer.core_data
enum class Style(val value: String) {
    ALTBIER("Altbier"),
    AUSTRALIAN_SPARKLING_ALE("Australian Sparkling Ale"),
    BARLEYWINE_AMERICAN("Barleywine - American"),
    BARLEYWINE_ENGLISH("Barleywine - English"),
    BARLEYWINE_OTHER("Barleywine - Other"),
    BELGIAN_BLONDE("Belgian Blonde"),
    BELGIAN_DUBBEL("Belgian Dubbel"),
    BELGIAN_ENKEL_PATERSBIER("Belgian Enkel / Patersbier"),
    BELGIAN_QUADRUPLE("Belgian Quadrupel"),
    BELGIAN_STRONG_DARK_ALE("Belgian Strong Dark Ale"),
    BELGIAN_STRONG_GOLDEN_ALE("Belgian Strong Golden Ale"),
    BELGIAN_TRIPEL("Belgian Tripel"),
    BITTER_BEST("Bitter - Best"),
    BITTER_EXTRA_SPECIAL_STRONG_ESB("Bitter - Extra Special / Strong (ESB)"),
    BITTER_SESSION_ORDINARY("Bitter - Session / Ordinary"),
    BIERE_DE_CHAMPAGNE_BIERE_BRUT("Biere De Champagne / Biere Brut"),
    BLACK_AND_TAN("Black & Tan"),
    BLONDE_ALE("Blonde Ale"),
    BOCK_DOPPELBOCK("Bock - Doppelbock"),
    BOCK_EISBOCK("Bock - Eisbock"),
    BOCK_HELL_MAIBOCK_LENTEBOCK("Bock - Hell / Maibock Lentebock"),
    BOCK_SINGLE_TRADITIONAL("Bock - Single/Traditional"),
    BOCK_WEIZENBOCK("Bock - Weizenbock"),
    BOCK_WEIZENDOPPELBOCK("Bock - Weizendoppelbock"),
    BRETT_BEER("Brett Beer"),
    BROWN_ALE_AMERICA("Brown Ale - America"),
    BROWN_ALE_BELGIAN("Brown Ale - Belgian"),
    BROWN_ALE_ENGLISH("Brown Ale - English"),
    BROWN_ALE_IMPERIAL_DOUBLE("Brown Ale - Imperial / Double"),
    BROWN_ALE_OTHER("Brown Ale - Other"),
    CALIFORNIA_COMMON("California Common"),
    CHILLI_CHILE_BEER("Chilli Chile Beer"),
    CIDER_DRY("Cider - Dry"),
    CIDER_GRAFF("Cider - Graff"),
    CIDER_HERBED_SPICED_HOPPED("Cider - Herbed / Spiced/Hopped"),
    CIDER_ICE_APPLEWINE("Cider - Ice / Applewine"),
    CIDER_OTHER_FRUIT("Cider - Other Fruit"),
    CIDER_PERRY("Cider - Perry"),
    CIDER_ROSE("Cider - Rosé"),
    CIDER_SWEET("Cider - Sweet"),
    CIDER_TRADITIONAL_APFELWEIN("Cider - Traditional / Apfelwein"),
    CORN_BEER_CHICHA_DE_JORA("Corn Beer / Chicha De Jora"),
    CREAM_ALE("Cream Ale"),
    DAR_KALE("Dark Ale"),
    FARM_HOUSE_ALE_BIERE_DE_COUPAGE("Farmhouse Ale - Biere De Coupage"),
    FARM_HOUSE_ALE_BIERE_DE_MARS("Farmhouse Ale - Biere De Mars"),
    FARMHOUSE_ALE_BIERE_DE_GARDE("Farmhouse Ale - Biere De Garde"),
    FARMHOUSE_ALE_GRITTE("Farmhouse Ale - Gritte"),
    FARMHOUSE_ALE_OTHER("Farmhouse Ale - Other"),
    FARMHOUSE_ALE_SAHTI("Farmhouse Ale - Sahti"),
    FARMHOUSE_ALE_SAISO("Farmhouse Ale - Saiso"),
    FESTBIER("Festbier"),
    FLAVORED_MALT_BEVERAGE("Flavored Malt Beverage"),
    FREEZE_DISTILLED_BEER("Freeze-Distilled Beer"),
    FRUIT_BEER("Fruit Beer"),
    GLUTEN_FREE("Gluten-Free"),
    GOLDEN_ALE("Golden Ale"),
    GRAPE_ALE_ITALIAN("Grape Ale - Italian"),
    GRAPE_ALE_OTHER("Grape Ale - Other"),
    GRODZISKIE_GRATZER("Grodziskie/ Grätzer"),
    HAPPOSHU("Happoshu"),
    HARD_GINGER_BEER("Hard Ginger Beer"),
    HARD_KOMBUCHA_JUN("Hard Kombucha / Jun"),
    HARD_SELTZER("Hard Seltzer"),
    HISTORICAL_BEER_ADAMBIER("Historical Beer - Adambier"),
    HISTORICAL_BEER_BERLINER_BRAUNBIER("Historical Beer - Berliner Braunbier"),
    HISTORICAL_BEER_BURTONALE("Historical Beer - Burton Ale"),
    HISTORICAL_BEER_DAMPFBIER("Historical Beer - Dampfbier"),
    HISTORICAL_BEER_GRUIT_ANCIENHERBED_ALE("Historical Beer - Gruit / AncienHerbed Ale"),
    HISTORICAL_BEER_KENTUCKY_COMMON("Historical Beer - Kentucky Common"),
    HISTORICAL_BEER_KOTTBUSSER("Historical Beer - Kottbusser"),
    HISTORICAL_BEER_LICHTENHAINE("Historical Beer - Lichtenhaine"),
    HISTORICAL_BEER_MUM("Historical Beer - Mum"),
    HISTORICAL_BEER_OTHER("Historical Beer - Other"),
    HISTORICAL_BEER_STEINBIER("Historical Beer - Steinbier"),
    HISTORICAL_BEER_ZOIGL("Historical Beer - Zoigl"),
    HONEY_BEER("Honey Beer"),
    IPA_AMERICAN("IPA - American"),
    IPA_BELGIAN("IPA - Belgian"),
    IPA_BLACK_CASCADIAN_DARK_ALE("IPA-Black / Cascadian Dark Ale"),
    IPA_BRETT("IPA - Brett"),
    IPA_BRUT("IPA - Brut"),
    IPA_COLD("IPA - Cold"),
    IPA_ENGLISH("IPA - English"),
    IPA_FARMHOUSE("IPA - Farmhouse"),
    IPA_IMPERIAL_DOUBLE("IPA - Imperial / Double"),
    IPA_IMPERIAL_DOUBLE_BLACK("IPA - Imperial / Double Black"),
    IPA_IMPERIAL_DOUBLE_MILKSHAKE("IPA - Imperial / Double Milkshake"),
    IPA_IMPERIAL_DOUBLE_NEW_ENGLAND_HAZY("IPA - Imperial / Double New England / Hazy"),
    IPA_MILKSHAKE("IPA - Milkshake"),
    IPA_NEW_ENGLAND_HAZY("IPA - New England / Hazy"),
    IPA_NEW_ZEALAND("IPA - New Zealand"),
    IPA_OTHER("IPA - Other"),
    IPA_QUADRUPLE("IPA - Quadruple"),
    IPA_RED("IPA - Red"),
    IPA_RYE("IPA - Rye"),
    IPA_SESSION("IPA - Session"),
    IPA_SOUR("IPA - Sour"),
    IPA_TRIPLE("IPA - Triple"),
    IPA_TRIPLE_NEW_ENGLAND_HAZY("IPA - Triple New England / Hazy"),
    IPA_WHITE_WHEAT("IPA - White / Wheat"),
    KELLERBIER_ZWICKELBIER("Kellerbier / Zwickelbier"),
    KOJI_GINJO_BEER("Koji / Ginjo Beer"),
    KVASS("Kvass"),
    KOLSCH("Kölsch"),
    LAGER_AMBER("Lager - Amber"),
    LAGER_AMERICAN("Lager - American"),
    LAGER_AMERICAN_AMBER_RED("Lager - American Amber Red"),
    LAGER_AMERICAN_LIGHT("Lager - American Light"),
    LAGER_DARK("Lager - Dark"),
    LAGER_DORTMUNDER_EXPORT("Lager - Dortmunder / Export"),
    LAGER_HELLES("Lager - Helles"),
    LAGER_IPL("Lager - IPL (India Pale Lager)"),
    LAGER_JAPANESEICE("Lager - Japaneseice"),
    LAGER_LEICHTBIER("Lager - Leichtbier"),
    LAGER_MEXICAN("Lager - Mexican"),
    LAGER_MUNICH_DUNKEL("Lager - Munich Dunkel"),
    LAGER("Lager"),
    LAGER_RED("Lager - Red"),
    LAGER_STRONG("Lager - Strong"),
    LAGER_VIENNA("Lager - Vienna"),
    LAGER_WINTER("Lager - Winter"),
    LAMBIC_FARO("Lambic - Faro"),
    LAMBIC_FRAMBOISE("Lambic - Framboise"),
    LAMBIC_FRUIT("Lambic - Fruit"),
    LAMBIC_GUEUZE("Lambic - Gueuze"),
    LAMBIC_KRIEK("Lambic - Kriek"),
    LAMBIC_OTHER("Lambic - Other"),
    LAMBIC_TRADITIONAL("Lambic - Traditional"),
    MALT_BEER("Malt Beer"),
    MALT_LIQUOR("Malt Liquor"),
    MEAD_ACERGLYN_MAPLE_WINE("Mead - Acerglyn/ Maple Wine"),
    MEAD_BOCHET("Mead - Bochet"),
    MEAD_BRAGGOT("Mead - Braggot"),
    MEAD_CYSER("Mead - Cyser"),
    MEAD_MELOMEL("Mead - Melomel"),
    MEAD_METHEGLIN("Mead - Metheglin"),
    MEAD_OTHER("Mead - Other"),
    MEAD_PYMEN("Mead - Pymen"),
    MEAD_SESSION_SHORT("Mead - Session / Short"),
    MEAD_TRADITIONA("Mead - Traditiona"),
    MILD_DAR("Mild - Dar"),
    MILD_LIGHT("Mild - Light"),
    MILD_OTHER("Mild - Other"),
    MARZEN("Märzen"),
    NON_ALCOHOLIC_BEER_IPA("Non-Alcoholic Beer - IPA"),
    NON_ALCOHOLIC_BEER_LAGER("Non-Alcoholic Beer - Lager"),
    NON_ALCOHOLIC_BEER_OTHER("Non-Alcoholic Beer - Other"),
    NON_ALCOHOLIC_BEER_PALE_ALE("Non-Alcoholic Beer - Pale Ale"),
    NON_ALCOHOLIC_BEER_PORTER_STOUT("Non-Alcoholic Beer - Porter / Stout"),
    NON_ALCOHOLIC_BEER_SHANDY_RADLER("Non-Alcoholic Beer Shandy Radler"),
    NON_ALCOHOLIC_BEER_SOUR("Non-Alcoholic Beer Sour"),
    NON_ALCOHOLIC_BEER_WHEAT_BEER("Non-Alcoholic Beer - Wheat Beer"),
    NON_ALCOHOLIC_CIDER_PERRY("Non-Alcoholic Cider / Perry"),
    NON_ALCOHOLIC_MEAD("Non-Alcoholic Mead"),
    OLD_ALE("Old Ale"),
    PALE_ALE_AMERICAN("Pale Ale - American"),
    PALE_ALE_AUSTRALIAN("Pale Ale - Australian"),
    PALE_ALE_BELGIAN("Pale Ale - Belgian"),
    PALE_ALE_ENGLISH("Pale Ale - English"),
    PALE_ALE_MILKSHAKE("Pale Ale - Milkshake"),
    PALE_ALE_NEW_ENGLAND_HAZY("Pale Ale - New England / Hazy"),
    PALE_ALE_NEW_ZEALAND("Pale Ale - New Zealand"),
    PALE_ALE_OTHER("Pale Ale - Other"),
    PALE_ALE_XPA("Pale Ale - XPA (Extra Pale)"),
    PILSNER_CZECH("Pilsner - Czech"),
    PILSNER_GERMAN("Pilsner - German"),
    PILSNER_IMPERIAL_DOUBLE("Pilsner - Imperial / Double"),
    PILSNER_ITALIA("Pilsner - Italia"),
    PILSNER_OTHER("Pilsner - Other"),
    PORTER_AMERICAN("Porter - American"),
    PORTER_BALTIC("Porter - Baltic"),
    PORTER_COFFEE("Porter - Coffee"),
    PORTER_ENGLISH("Porter - English"),
    PORTER_IMPERIAL_DOUBLE("Porter - Imperial / Double"),
    PORTER_IMPERIAL_DOUBLE_BALTIC("Porter - Imperial / Double Baltic"),
    PORTER_IMPERIAL_DOUBLE_COFFEE("Porter - Imperial / Double Coffee"),
    PORTER_OTHER("Porter - Other"),
    PUMPKIN_YAM_BEER("Pumpkin / Yam Beer"),
    RAUCHBIER("Rauchbier"),
    RED_ALE_AMERICAN_AMBER_RED("Red Ale - American Amber / Red"),
    RED_ALE_IMPERIAL_DOUBLE("Red Ale - Imperial / Double"),
    RED_ALE_IRISH("Red Ale - Irish"),
    RED_ALE_OTHER("Red Ale - Other"),
    ROGGENBIER("Roggenbier"),
    ROOT_BEER("Root Beer"),
    RYE_BEER("Rye Beer"),
    RYE_WINE("Rye Wine"),
    SCHWARZBIER("Schwarzbier"),
    SCOTCH_ALE_WEE_HEAVY("Scotch Ale / Wee Heavy"),
    SCOTTISH_ALE("Scottish Ale"),
    SCOTTISH_EXPORT_ALE("Scottish Export Ale"),
    SHANDY_RADLER("Shandy / Radler"),
    SMOKED_BEER("Smoked Beer"),
    SORGHUM_MILLET_BEER("Sorghum / Millet Beer"),
    SOUR_BERLINER_WEISSE("Sour Berliner Weisse"),
    SOUR_FLANDERS_OUD_BRUIN("Sour - Flanders Oud Bruin"),
    SOUR_FLANDERS_RED_ALE("Sour - Flanders Red Ale"),
    SOUR_FRUITED("Sour - Fruited"),
    SOUR_FRUITED_BERLINER_WEISSE("Sour- Fruited Berliner Weisse"),
    SOUR_FRUITED_GOSE("Sour - Fruited Gose"),
    SOUR_OTHER("Sour - Other"),
    SOUR_OTHER_GOSE("Sour - Other Gose"),
    SOUR_SMOOTHIE_PASTRY ("Sour - Smoothie / Pastry"),
    SOUR_TRADITIONAL_GOSE ("Sour-Traditional Gose"),
    SPECIALTY_GRAIN ("Specialty Grain"),
    SPICED_HERBED_BEER ("Spiced/Herbed Beer"),
    STOUT_AMERICAN ("Stout - American"),
    STOUT_COFFEE ("Stout - Coffee"),
    STOUT_ENGLISH ("Stout - English"),
    STOUT_FOREIGN_EXPORT ("Stout - Foreign / Export"),
    STOUT_IMPERIAL_DOUBLE ("Stout - Imperial / Double"),
    STOUT_IMPERIAL_DOUBLE_COFFEE ("Stout - Imperial / Double Coffee"),
    STOUT_IMPERIAL_DOUBLE_MILK ("Stout - Imperial / Double Milk"),
    STOUT_IMPERIAL_DOUBLE_OATMEAL ("Stout - Imperial / Double Oatmeal"),
    STOUT_IMPERIAL_DOUBLE_PASTRY ("Stout - Imperial / Double Pastry"),
    STOUT_IMPERIAL_DOUBLE_WHITE_GOLDEN ("Stout - Imperial / Double White / Golden"),
    STOUT_IRISH_DRY ("Stout - Irish Dry"),
    STOUT_MILK_SWEET ("Stout - Milk/ Sweet"),
    STOUT_OATMEAL ("Stout - Oatmeal"),
    STOUT_OTHER ("Stout - Other"),
    STOUT_OYSTER ("Stout - Oyster"),
    STOUT_PASTRY ("Stout - Pastry"),
    STOUT_RUSSIAN_IMPERIAL ("Stout - Russian Imperial"),
    STOUT_WHITE_GOLDEN ("Stout - White/Golden"),
    STRONG_ALE_AMERICAN ("Strong Ale - American"),
    STRONG_ALE_ENGLISH ("Strong Ale - English"),
    STRONG_ALE_OTHER ("Strong Ale - Other"),
    TABLE_BEER ("Table Beer"),
    TRADITIONAL_ALE ("Traditional Ale"),
    UKRAINIAN_GOLDEN_ALE ("Ukrainian Golden Ale"),
    WHEAT_BEER_AMERICAN_PALE_WHEAT ("Wheat Beer - American Pale Wheat"),
    WHEAT_BEER_DUNKELWEIZEN ("Wheat Beer - Dunkelweizen"),
    WHEAT_BEER_HEFEWEIZEN ("Wheat Beer - Hefeweizen"),
    WHEAT_BEER_HEFEWEIZEN_LIGHT_LEICHT ("Wheat Beer - Hefeweizen Light/Leicht"),
    WHEAT_BEER_HOPFENWEISSE ("Wheat Beer - Hopfenweisse"),
    WHEAT_BEER_KRISTALLWEIZEN ("Wheat Beer - Kristallweizen"),
    WHEAT_BEER_OTHER("Wheat Beer - Other"),
    WHEAT_BEER_WHEAT_WI("Wheat Beer - Wheat Wi"),
    WHEAT_BEER_WITBIER_BLANCHE("Wheat Beer - Witbier / Blanche"),
    WILD_ALE_AMERICAN("Wild Ale - American"),
    WILD_ALE_OTHER("Wild Ale - Other"),
    WINTER_ALE("Winter Ale"),
    WINTER_WARMER("Winter Warmer");

    companion object {
        infix fun from(value: String): Style = Style.values().first { it.value == value }
    }
}